local InstanceTypes = {
	Nil = 1,
	Model = 2,
	Folder = 3,
	Part = 4,
	PartNoAttributes = 5,
	BoolValue = 6,
	WedgePart = 7,
	StringValue = 8,
	MeshPart = 9,
	UnionOperation = 10,
	Texture = 11,
	BlockMesh = 12,
	PointLight = 13,
	SpotLight = 14,
	SurfaceLight = 15,
	SpecialMesh = 16,
	Decal = 17,
	Fire = 18,
	Smoke = 19,
	Attachment = 20,
	ParticleEmitter = 21,
	Sparkles = 22,
	SurfaceGui = 23,
	ImageLabel = 24,
	BillboardGui = 25,
	Frame = 26,
	Beam = 27,
	Trail = 28,
	NegateOperation = 29,
}

return InstanceTypes