local InstanceProperties

-- Format:
-- [TypeName], [ValueType], [DefaultValue]
-- eg. "Position", "Vector3", "Vector3.new(0, 0, 0)"

InstanceProperties = { -- any changes to this table should be changed in InstanceTypes.lua, WriteInstance.lua, and ReadInstance.lua
	Model = {
		{ "Name", "String", "Model" },
	},
	Folder = {
		{ "Name", "String", "Folder" },
	},
	Part = {
		{ "Name", "String", "Part" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Color", "Color3", Color3.new() },
		{ "Size", "Vector3", Vector3.new() },
		{ "Anchored", "Bool", true },
		{ "CanCollide", "Bool", true },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "Material", "Material", "Plastic" },
		{ "CastShadow", "Bool", false },
		{ "Shape", "PartType", "Block" },
		{ "AssemblyLinearVelocity", "Vector3", Vector3.new()},
		{ "AssemblyAngularVelocity", "Vector3", Vector3.new()},
	},
	BoolValue = {
		{ "Name", "String", "Value" },
		{ "Value", "Bool", false },
	},
	WedgePart = {
		{ "Name", "String", "Wedge" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Color", "Color3", Color3.new() },
		{ "Size", "Vector3", Vector3.new() },
		{ "Anchored", "Bool", true },
		{ "CanCollide", "Bool", true },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "Material", "Material", "Plastic" },
		{ "CastShadow", "Bool", false },
	},
	StringValue = {
		{ "Name", "String", "StringValue" },
		{ "Value", "String", "" },
	},
	MeshPart = {
		{ "Name", "String", "Part" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Color", "Color3", Color3.new() },
		{ "Size", "Vector3", Vector3.new() },
		{ "Anchored", "Bool", true },
		{ "CanCollide", "Bool", true },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "Material", "Material", "Plastic" },
		{ "CastShadow", "Bool", false },
		{ "MeshId", "String", "" },
		{ "TextureID", "String", "" },
		{ "RenderFidelity", "RenderFidelity", "Automatic" },
		{ "CollisionFidelity", "CollisionFidelity", "Default" },
	},
	UnionOperation = {
		{ "Name", "String", "Part" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Color", "Color3", Color3.new() },
		{ "Size", "Vector3", Vector3.new() },
		{ "Anchored", "Bool", true },
		{ "CanCollide", "Bool", true },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "Material", "Material", "Plastic" },
		{ "CastShadow", "Bool", false },
		{ "MeshId", "String", "" },
		{ "UsePartColor", "Bool", false },
		{ "CSG", "CSG", {} }, -- Putting any properties after this breaks everything please someone help me why does this happen
	},
	Texture = {
		{ "Name", "String", "Texture" },
		{ "Color3", "Color3", Color3.new() },
		{ "OffsetStudsU", "Float", 0 },
		{ "OffsetStudsV", "Float", 0 },
		{ "StudsPerTileU", "Float", 0 },
		{ "StudsPerTileV", "Float", 0 },
		{ "Texture", "String", "" },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "ZIndex", "Int", 0 },
		{ "Face", "NormalId", "Front" },
	},
	BlockMesh = {
		{ "Scale", "Vector3", Vector3.new(1, 1, 1) },
		{ "Offset", "Vector3", Vector3.new(0, 0, 0) },
	},
	PointLight = {
		{ "Name", "String", "PointLight" },
		{ "Brightness", "Float", 1 },
		{ "Color", "Color3", Color3.new(1, 1, 1) },
		{ "Enabled", "Bool", true },
		{ "Range", "Float", 20 },
		{ "Shadows", "Bool", false },
	},
	SpotLight = {
		{ "Name", "String", "SpotLight" },
		{ "Angle", "Float", 90 },
		{ "Brightness", "Float", 1 },
		{ "Color", "Color3", Color3.new(1, 1, 1) },
		{ "Enabled", "Bool", true },
		{ "Face", "NormalId", Enum.NormalId.Front },
		{ "Range", "Float", 16 },
		{ "Shadows", "Bool", false },
	},
	SurfaceLight = {
		{ "Name", "String", "SurfaceLight" },
		{ "Angle", "Float", 90 },
		{ "Brightness", "Float", 1 },
		{ "Color", "Color3", Color3.new(1, 1, 1) },
		{ "Enabled", "Bool", true },
		{ "Face", "NormalId", Enum.NormalId.Front },
		{ "Range", "Float", 16 },
		{ "Shadows", "Bool", false },
	},
	SpecialMesh = {
		{ "Name", "String", "Mesh" },
		{ "MeshId", "String", "" },
		{ "MeshType", "MeshType", Enum.MeshType.FileMesh },
		{ "Offset", "Vector3", Vector3.new(0, 0, 0) },
		{ "Scale", "Vector3", Vector3.new(1, 1, 1) },
		{ "VertexColor", "Vector3", Vector3.new(1, 1, 1) },
		{ "TextureId", "String", "" },
	},
	Decal = {
		{ "Name", "String", "Decal" },
		{ "Color3", "Color3", Color3.new() },
		{ "Texture", "String", "" },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "ZIndex", "Int", 0 },
		{ "Face", "NormalId", Enum.NormalId.Front },
	},
	Fire = {
		{ "Name", "String", "Fire" },
		{ "Color", "Color3", Color3.new() },
		{ "Enabled", "Bool", true },
		{ "Heat", "Float", 9 },
		{ "SecondaryColor", "Color3", Color3.new() },
		{ "Size", "Float", 5 },
		{ "TimeScale", "Float", 1 },
	},
	Smoke = {
		{ "Name", "String", "Smoke" },
		{ "Color", "Color3", Color3.new() },
		{ "Enabled", "Bool", true },
		{ "Opacity", "Float", 1 },
		{ "RiseVelocity", "Float", 1 },
		{ "Size", "Float", 1 },
		{ "TimeScale", "Float", 1 },
	},
	Attachment = {
		{ "Name", "String", "Attachment" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Visible", "Bool", false },
	},
	ParticleEmitter = {
		{ "Name", "String", "ParticleEmitter" },
		{ "Color", "ColorSequence", ColorSequence.new(Color3.new(1, 1, 1)) },
		{ "Size", "FloatSequence", NumberSequence.new(1) },
		{ "Texture", "String", "rbxasset://textures/particles/sparkles_main.dds" },
		{ "Transparency", "FloatSequence", NumberSequence.new(1) },
		{ "Orientation", "ParticleOrientation", Enum.ParticleOrientation.FacingCamera},
		{ "Rate", "Float", 20 },
		{ "Rotation", "FloatRange", NumberRange.new(0) },
		{ "RotSpeed", "FloatRange", NumberRange.new(0) },
		{ "Shape", "ParticleEmitterShape", Enum.ParticleEmitterShape.Box },
		{ "ShapeInOut", "ParticleEmitterShapeInOut", Enum.ParticleEmitterShapeInOut.Outward },
		{ "ShapePartial", "Float", 1 },
		{ "ShapeStyle", "ParticleEmitterShapeStyle", Enum.ParticleEmitterShapeStyle.Volume },
		{ "Speed", "FloatRange", NumberRange.new(5) },
		{ "Lifetime", "FloatRange", NumberRange.new(5, 10) },
		{ "EmissionDirection", "NormalId", Enum.NormalId.Top },
		{ "SpreadAngle", "Vector2", Vector2.new(0, 0) },
		{ "Acceleration", "Vector3", Vector3.new(0, 0, 0) },
		{ "Brightness", "Float", 1 },
		{ "Squash", "FloatSequence", NumberSequence.new(0) }
	},
	Sparkles = {
		{ "Name", "String", "Sparkles" },
		{ "SparkleColor", "Color3", Color3.new(144, 25, 255) },
		{ "TimeScale", "Float", 1 },
	},
	SurfaceGui = {
		{ "Name", "String", "SurfaceGui" },
		{ "Face", "NormalId", Enum.NormalId.Front },
		{ "Brightness", "Float", 1 },
		{ "LightInfluence", "ShortBoundedFloat", 0.5 },
		{ "MaxDistance", "Int", 0 },
		{ "ClipsDescendants", "Bool", true },
		{ "SizingMode", "SurfaceGuiSizingMode", Enum.SurfaceGuiSizingMode.PixelsPerStud }
	},
	ImageLabel = {
		{ "Name", "String", "ImageLabel" },

		{ "Position", "UDim2", UDim2.new() },
		{ "Size", "UDim2", UDim2.new() },
		{ "Rotation", "Float", 0 },
		{ "AnchorPoint", "Vector2", Vector2.new() },
		{ "BackgroundColor3", "Color3", Color3.new() },
		{ "BackgroundTransparency", "ShortBoundedFloat", 0 },
		{ "BorderSizePixel", "Int", 0 },
		{ "ClipsDescendants", "Bool", false },
		{ "ZIndex", "Int", 0 },

		{ "Image", "String", "" },
		{ "ImageTransparency", "ShortBoundedFloat", 0 },
		{ "ImageRectOffset", "Vector2", Vector2.new() },
		{ "ImageRectSize", "Vector2", Vector2.new() },
		{ "ResampleMode", "ResamplerMode", Enum.ResamplerMode.Default },
	},
	BillboardGui = {
		{ "Name", "String", "BillboardGui" },
		{ "Adornee", "InstanceReference", nil },
		{ "AlwaysOnTop", "Bool", false },
		{ "Enabled", "Bool", true },
		{ "ExtentsOffset", "Vector3", Vector3.new(0, 0, 0) },
		{ "ExtentsOffsetWorldSpace", "Vector3", Vector3.new(0, 0, 0) },
		{ "LightInfluence", "ShortBoundedFloat", 1 },
		{ "MaxDistance", "Int", math.huge },
		{ "Size", "UDim2", UDim2.new(0, 200, 0, 50) },
		{ "SizeOffset", "Vector2", Vector2.new(0, 0) },
		{ "StudsOffset", "Vector3", Vector3.new(0, 0, 0) },
		{ "StudsOffsetWorldSpace", "Vector3", Vector3.new(0, 0, 0) },
		{ "ClipsDescendants", "Bool", true },
	},
	Frame = {
		{ "Name", "String", "ImageLabel" },
		{ "Position", "UDim2", UDim2.new(0, 0, 0, 0) },
		{ "Size", "UDim2", UDim2.new(0, 100, 0, 100) },
		{ "Rotation", "Float", 0 },
		{ "AnchorPoint", "Vector2", Vector2.new() },
		{ "BackgroundColor3", "Color3", Color3.new() },
		{ "BackgroundTransparency", "ShortBoundedFloat", 0 },
		{ "BorderSizePixel", "Int", 0 },
		{ "ClipsDescendants", "Bool", false },
		{ "ZIndex", "Int", 0 },
	},
	Beam = {
		{ "Color", "ColorSequence", ColorSequence.new(Color3.new(1, 1, 1)) },
		{ "Enabled", "Bool", true },
		{ "LightEmission", "Float", 0 },
		{ "LightInfluence", "Float", 1 },
		{ "Texture", "String", "" },
		{ "TextureLength", "Float", 1 },
		{ "TextureMode", "TextureMode", Enum.TextureMode.Stretch },
		{ "TextureSpeed", "Float", 1 },
		{ "Transparency", "FloatSequence", NumberSequence.new(0.5) },
		{ "ZOffset", "Float", 0 },
		{ "Name", "String", "Beam" },
		{ "Attachment0", "InstanceReference", nil },
		{ "Attachment1", "InstanceReference", nil },
		{ "CurveSize0", "Float", 0 },
		{ "CurveSize1", "Float", 0 },
		{ "FaceCamera", "Bool", false },
		{ "Segments", "Float", 10 },
		{ "Width0", "Float", 1 },
		{ "Width1", "Float", 1 },
	},
	Trail = {
		{ "Color", "ColorSequence", ColorSequence.new(Color3.new(1, 1, 1)) },
		{ "FaceCamera", "Bool", false },
		{ "LightEmission", "Float", 0 },
		{ "LightInfluence", "Float", 1 },
		{ "Texture", "String", "" },
		{ "TextureLength", "Float", 1 },
		{ "TextureMode", "TextureMode", Enum.TextureMode.Stretch },
		{ "Transparency", "FloatSequence", NumberSequence.new(0.5) },
		{ "Attachment0", "InstanceReference", nil },
		{ "Attachment1", "InstanceReference", nil },
		{ "Name", "String", "Trail" },
		{ "Enabled", "Bool", true },
		{ "Lifetime", "Float", 2 },
		{ "MaxLength", "Float", 0 },
		{ "MinLength", "Float", 0.1 },
		{ "WidthScale", "FloatSequence", NumberSequence.new(1) },
	},
	NegateOperation = {
		{ "Name", "String", "Part" },
		{ "CFrame", "CFrame", CFrame.new() },
		{ "Color", "Color3", Color3.new() },
		{ "Size", "Vector3", Vector3.new() },
		{ "Anchored", "Bool", true },
		{ "CanCollide", "Bool", true },
		{ "Transparency", "ShortBoundedFloat", 0 },
		{ "Material", "Material", "Plastic" },
		{ "CastShadow", "Bool", false },
		--{ "Shape", "PartType", "Block" },
	},
}

return InstanceProperties